language: cpp
sudo: false
dist: bionic

script:
  - make

matrix:
  include:
    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - xcb
            - xcb-proto
            - libx11-dev
            - libx11-xcb-dev
            - libxcb1-dev
            - libxcb-util-dev
            - libxcb-icccm4-dev
            - libxcb-randr0-dev
            - libxcb-keysyms1-dev

      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - xcb
            - xcb-proto
            - libx11-dev
            - libx11-xcb-dev
            - libxcb1-dev
            - libxcb-util-dev
            - libxcb-icccm4-dev
            - libxcb-randr0-dev
            - libxcb-keysyms1-dev

      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

before_install:
  - eval "${MATRIX_EVAL}"

addons:
  apt:
    packages:
    - libx11-xcb-dev
    - libxcb-util0-dev
    - libxcb-icccm4-dev
    - libxcb-randr0-dev
    - libxcb-keysyms1-dev
