os: linux
dist: bionic
language: cpp
compiler:
  - g++
  - clang++

jobs:
	include:
		- name: "gcc-9"
		compiler: g++
		addons:
			apt:
				sources:
					- ubuntu-toolchain-r-test
					- sourceline: ppa:ubuntu-toolchain-r/test
				packages:
					- g++-9
				env:
					JOBS_EVAL="CXX=g++-9"

		- name: "clang-9"
		compiler: clang++
		addons:
			apt:
				sources:
					- llvm-toolchain-bionic-9
					- sourceline: ppa:ubuntu-toolchain-r/test
				packages:
					- clang++-9
				env:
					JOBS_EVAL="CXX=clang++-9"


addons:
  apt:
    packages:
    - libx11-xcb-dev
    - libxcb-util-dev
    - libxcb-icccm4-dev
    - libxcb-randr0-dev
    - libxcb-keysyms1-dev

before_install:
	eval "${JOBS_EVAL}"
  # - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # - sudo apt-get update -qq

# install:
#   - sudo apt-get install -qq g++-8
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

script:
  - make
